language: r
r: bioc-devel
sudo: required
cache: packages
r_binary_packages:
  - lme4
  - multcomp
  - dplyr
  - tidyr
  - reshape2
  - magrittr
  - knitr
  - rmarkdown
  - mime
  - curl
  - openssl
  - R6
  - httr
  - memoise
  - whisker
  - digest
  - rstudioapi
  - jsonlite
  - git2r
  - withr